function eventinfo = readseloc(locfile)
%READSELOC reads .loc file generated by velest single event mode.
%   EVENTINFO = READSELOC(LOCFILE) opens a .loc file produced by velest
%   single event mode and outputs a structure EVENTINFO containing all the
%   information for each event in the .loc file. Currently P-wave pics
%   only.
%
% Example: eventinfo = readseloc(locfile);
%
% Written and last edited by Kyle Brill 2016/05/11 11:00:00 EDT

%% Initialize Variables

%% Preallocation

%% Read file into MATLAB
fileID = fopen(locfile,'r');
finfo = dir(locfile);

if isempty(finfo)
    error('LOC File Does Not Exist')
end

tmpline=fgetl(fileID);
while ischar(tmpline)
    if ~isempty(tmpline) && ~(length(tmpline)==1 && isstrprop(tmpline(1,1),'wspace'))
        if length(tmpline)==78
            eventnum = str2double(tmpline(1,24:28));
        elseif length(tmpline) == 80 && isstrprop(tmpline(1,1),'wspace')
            [yyyy,mm,dd] = datevec(['20' tmpline(1,2:7)],'yyyymmdd');
            origin = ...
                datenum(['20' tmpline(1,2:20)],'yyyymmdd HH:MM:SS.FFF');
            
            lat = str2double(tmpline(1,22:28));
            latc= tmpline(29);
            if strcmp(latc,'S')
                lat=-lat;
            end
            
            lon = str2double(tmpline(1,31:37));
            lonc= tmpline(38);
            if strcmp(lonc,'W')
                lon=-lon;
            end
            
            depth = str2double(tmpline(1,40:46));
            
            mag = str2double(tmpline(1,49:51));
            
            nobs = str2double(tmpline(1,53:55));
            
            dm = str2double(tmpline(1,57:59));
            
            gap = str2double(tmpline(1,61:63));
            
            rms = str2double(tmpline(1,65:68));
            
            ale = str2double(tmpline(1,70:74));
            
            dspr = str2double(tmpline(1,76:80));
            
        elseif length(tmpline) == 63 && isstrprop(tmpline(1,1),'wspace')
                
            erx = str2double(tmpline(1,3:6));
            
            ery = str2double(tmpline(1,8:11));
            
            erz = str2double(tmpline(1,13:16));
            
            q = tmpline(1,18);
            
            sqd = tmpline(1,20:22);
            
            adj = str2double(tmpline(1,24:28));
            
            inn = str2double(tmpline(1,30:31));
            
            nr = str2double(tmpline(1,33:34));
            
            avr = str2double(tmpline(1,36:40));
            
            aar = str2double(tmpline(1,42:46));
            
            nm = str2double(tmpline(1,49:50));
            
            avxm = str2double(tmpline(1,52:55));
            
            sdxm = str2double(tmpline(1,57:60));
            
            it = str2double(tmpline(1,61:63));
                
        elseif length(tmpline) == 90 && isstrprop(tmpline(1,1),'wspace')
            
            picks.(tmpline(1,3:6)).dist = str2double(tmpline(1,8:11));
            
            picks.(tmpline(1,3:6)).azm = str2double(tmpline(1,13:15));
            
            picks.(tmpline(1,3:6)).ain = str2double(tmpline(1,17:19));
            
            picks.(tmpline(1,3:6)).prmk = str2double(tmpline(1,24));
            
            hr = str2double(tmpline(1,26:27)); %pull out hours
            mn = str2double(tmpline(1,28:29)); %pull out minutes
            sf = str2double(tmpline(31:36)); %pull out minutes
            picks.(tmpline(1,3:6)).time = datenum(yyyy,mm,dd,hr,mn,sf);
            
            picks.(tmpline(1,3:6)).tpobs = str2double(tmpline(1,38:43));
            
            picks.(tmpline(1,3:6)).tpcal = str2double(tmpline(1,45:50));
            
            picks.(tmpline(1,3:6)).tscor = str2double(tmpline(1,52:57));
            
            picks.(tmpline(1,3:6)).pres = str2double(tmpline(1,59:65));
            
            picks.(tmpline(1,3:6)).pwt = str2double(tmpline(1,67:72));
            
            picks.(tmpline(1,3:6)).imp = str2double(tmpline(1,74:79));
            
            picks.(tmpline(1,3:6)).stures = str2double(tmpline(1,81:86));
            
        end
            
    elseif exist('eventnum','var')
        
        eventinfo(eventnum,1).origin = origin;
        eventinfo(eventnum,1).lat = lat;
        eventinfo(eventnum,1).lon = lon;
        eventinfo(eventnum,1).depth = depth;
        eventinfo(eventnum,1).mag = mag;
        eventinfo(eventnum,1).nobs = nobs;
        eventinfo(eventnum,1).dm = dm;
        eventinfo(eventnum,1).gap = gap;
        eventinfo(eventnum,1).rms = rms;
        eventinfo(eventnum,1).ale = ale;
        eventinfo(eventnum,1).dspr = dspr;
        eventinfo(eventnum,1).erx = erx;
        eventinfo(eventnum,1).ery = ery;
        eventinfo(eventnum,1).erz = erz;
        eventinfo(eventnum,1).q = q;
        eventinfo(eventnum,1).sqd = sqd;
        eventinfo(eventnum,1).adj = adj;
        eventinfo(eventnum,1).inn = inn;
        eventinfo(eventnum,1).nr = nr;
        eventinfo(eventnum,1).avr = avr;
        eventinfo(eventnum,1).aar = aar;
        eventinfo(eventnum,1).nm = nm;
        eventinfo(eventnum,1).avxm = avxm;
        eventinfo(eventnum,1).sdxm = sdxm;
        eventinfo(eventnum,1).it = it;
        eventinfo(eventnum,1).picks = picks;
        
        clearvars -except eventinfo fileID tmpline
        
    end
    
    tmpline=fgetl(fileID);
    
end