function [Lon,Lat,Ele] = xyzread(xyzfile, startRow, endRow)
%XYZREAD Import numeric data from a text file as column vectors.
%   [LON,LAT,ELE] = XYZREAD(XYZFILE) Reads data from text file XYZFILE
%   for the default selection.
%
%   [LON,LAT,ELE] = XYZREAD(XYZFILE, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file XYZFILE.
%
% Example:
%   [Lon,Lat,Ele] = xyzread('fgtopo-2Kdatum.xyz',1, 251001);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/05/05 13:29:30

%% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%11f%11f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(xyzfile,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Lon = dataArray{:, 1};
Lat = dataArray{:, 2};
Ele = dataArray{:, 3};


